### ISSUE TITLE
ClassCastException Crash due to Nature's Aura x Powah interaction

### ISSUE THREAD

**Issue by AmmoniumX** [EnigmaticaModpacks/Enigmatica9#870]
### Modpack Version

Enigmatica9-1.18.0

### Describe your issue.

Server crashes due to this ClassCastException due to an interaction between Nature's Aura and Powah:
```
java.lang.ClassCastException: class owmii.powah.forge.ForgeEnvHandler$7 cannot be cast to class de.ellpeck.naturesaura.api.aura.container.IAuraContainer (owmii.powah.forge.ForgeEnvHandler$7 is in module powah@4.0.11 of loader 'TRANSFORMER' @6e0d16a4; de.ellpeck.naturesaura.api.aura.container.IAuraContainer is in module naturesaura@38.2 of loader 'TRANSFORMER' @6e0d16a4)
	at de.ellpeck.naturesaura.chunk.effect.ReplenishingEffect.lambda$update$0(ReplenishingEffect.java:28) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading}
	at de.ellpeck.naturesaura.Helper.getBlockEntitiesInArea(Helper.java:71) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading,pl:runtimedistcleaner:A}
	at de.ellpeck.naturesaura.chunk.effect.ReplenishingEffect.update(ReplenishingEffect.java:27) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading}
	at de.ellpeck.naturesaura.chunk.AuraChunk.update(AuraChunk.java:160) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading}
	at de.ellpeck.naturesaura.events.CommonEvents.onLevelTick(CommonEvents.java:95) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading}
	at de.ellpeck.naturesaura.events.__CommonEvents_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[NaturesAura-38.2.jar%23451!/:38.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.2.14-universal.jar%23542!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23537!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23537!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23537!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23537!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23537!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```

I have a slight suspicion of what the problem is, it might be because I powered one of the EnigmaticUnity resonating crystals directly with a Powah ender gate, that is the only instance of Powah and Nature's Aura interacting that I can currently think of

### Crash Report

https://mclo.gs/X0tvdkV

### Latest Log

https://mclo.gs/vwv2p1G

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

ammoniumx

**Comment by AmmoniumX** [comment]
Update: apparently this issue is caused by the AECapFix mod, removing it fixes it:
https://github.com/Technici4n/Powah/issues/137
