### ISSUE TITLE
KubeJS Error on startup while registering potions

### ISSUE THREAD

**Issue by ctembreull** [EnigmaticaModpacks/Enigmatica9#893]
### Modpack Version

1.19.1

### Describe your issue.

Not sure what's happening here; the potions scripts looked normal.

```
[13:50:14] [ERROR] ! Error occurred while handling event 'MoreJSEvents.registerPotionBrewing': java.lang.IllegalArgumentException: Ingredient must have at least one item
[13:50:14] [ERROR] ! java.lang.IllegalArgumentException: Ingredient must have at least one item
[13:50:14] [ERROR] ! 	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[13:50:14] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.features.potion.PotionBrewingRegisterEvent.validateSimple(PotionBrewingRegisterEvent.java:33)
[13:50:14] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.features.potion.PotionBrewingRegisterEventForge.addPotionBrewing(PotionBrewingRegisterEventForge.java:31)
[13:50:14] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:50:14] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:50:14] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:50:14] [ERROR] ! 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.NativeArray.iterativeMethod(NativeArray.java:1314)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.NativeArray.execIdCall(NativeArray.java:1798)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.IdFunctionObject.call(IdFunctionObject.java:103)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1197)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:2619)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:129)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:88)
[13:50:14] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.2-build.280/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[13:50:14] [ERROR] ! 	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy97.onEvent(Unknown Source)
[13:50:14] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[13:50:14] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[13:50:14] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:271)
[13:50:14] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[13:50:14] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.63/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:178)
[13:50:14] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.MoreJSForge.onClientCommon(MoreJSForge.java:31)
[13:50:14] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
[13:50:14] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
[13:50:14] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[13:50:14] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[13:50:14] [ERROR] ! 	at LAYER PLUGIN/javafmllanguage@1.19.2-43.2.14/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107)
[13:50:14] [ERROR] ! 	at LAYER PLUGIN/fmlcore@1.19.2-43.2.14/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[13:50:14] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

### Latest Log

https://gist.github.com/ctembreull/d129360f4044b181839b3ad50133f30c

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report! This generally happens when one of the custom ingredients doesn't exist. That would generally suggest that the mod that the item comes from is missing.

I'd suggest starting with a reinstall and see where that takes you.

**Comment by ctembreull** [comment]
Thanks for this - I did the reinstall and based on your suggestion, I found that my pack manager, when it encounters mods that disallow automatic downloading, presents a strangely-sized dialog with no indication of *how many* mods are still needed. So it's a combination of user error and poor interface design on the part of a launcher.

It's working now.

**Comment by MommyHeather** [comment]
Just out of curiosity, what pack manager is that?

**Comment by ctembreull** [comment]
I'm using Prism Launcher at the moment.

**Comment by MommyHeather** [comment]
I mean, Prism does provide a) a scrollbar and b) a "download all" button..?

Though, I do think that the starting size of that popup should be bigger.

**Comment by ctembreull** [comment]
Perhaps better to say clearly "There are X mods that require manual download", and/or make the popup larger and less busy, so as to make clear that there are multiple actions the user needs to take. The initial popup size can make it look as if there's only one that needs to be handled. Anyway, it's solved now and I'm wise to one of Prism's issues.

**Comment by ctembreull** [comment]
Also... on Prism latest (8.2) there is no "download all" button in the blocked mods dialog for Curseforge packs. Each download link needs to be opened individually by clicking the links provided in the dialog. Which works fine, up until you can't see subsequent entries in the list.

Might be a good issue for the Prism team. 

<img width="737" alt="Screenshot 2024-03-09 at 11 17 07 PM" src="https://github.com/EnigmaticaModpacks/Enigmatica9/assets/762105/1560447f-f257-4f20-b471-d0fc4d691110">

**Comment by MommyHeather** [comment]
Ah, my apologies there - it's the "open missing" in your screenshot, I got the labelling wrong.
